import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['var(--font-plus-jakarta-sans)', 'sans-serif'],
      },
      colors: {
        'slate-50': 'var(--slate-50)',
        'slate-900': 'var(--slate-900)',
        'royal-blue': 'var(--royal-blue)',
        'indigo-accent': 'var(--indigo-accent)',
        'teal-accent': 'var(--teal-accent)',
        'sunset-orange': 'var(--sunset-orange)',
        'surface': 'var(--surface)',
        'surface-dim': 'var(--surface-dim)',
        'surface-bright': 'var(--surface-bright)',
        'surface-container-lowest': 'var(--surface-container-lowest)',
        'surface-container-low': 'var(--surface-container-low)',
        'surface-container': 'var(--surface-container)',
        'surface-container-high': 'var(--surface-container-high)',
        'surface-container-highest': 'var(--surface-container-highest)',
        'on-surface': 'var(--on-surface)',
        'on-surface-variant': 'var(--on-surface-variant)',
        'inverse-surface': 'var(--inverse-surface)',
        'inverse-on-surface': 'var(--inverse-on-surface)',
        'outline': 'var(--outline)',
        'outline-variant': 'var(--outline-variant)',
        'surface-tint': 'var(--surface-tint)',
        'primary': 'var(--primary)',
        'on-primary': 'var(--on-primary)',
        'primary-container': 'var(--primary-container)',
        'on-primary-container': 'var(--on-primary-container)',
        'inverse-primary': 'var(--inverse-primary)',
        'secondary': 'var(--secondary)',
        'on-secondary': 'var(--on-secondary)',
        'secondary-container': 'var(--secondary-container)',
        'on-secondary-container': 'var(--on-secondary-container)',
        'tertiary': 'var(--tertiary)',
        'on-tertiary': 'var(--on-tertiary)',
        'tertiary-container': 'var(--tertiary-container)',
        'on-tertiary-container': 'var(--on-tertiary-container)',
        'error': 'var(--error)',
        'on-error': 'var(--on-error)',
        'error-container': 'var(--error-container)',
        'on-error-container': 'var(--on-error-container)',
        'primary-fixed': 'var(--primary-fixed)',
        'primary-fixed-dim': 'var(--primary-fixed-dim)',
        'on-primary-fixed': 'var(--on-primary-fixed)',
        'on-primary-fixed-variant': 'var(--on-primary-fixed-variant)',
        'secondary-fixed': 'var(--secondary-fixed)',
        'secondary-fixed-dim': 'var(--secondary-fixed-dim)',
        'on-secondary-fixed': 'var(--on-secondary-fixed)',
        'on-secondary-fixed-variant': 'var(--on-secondary-fixed-variant)',
        'tertiary-fixed': 'var(--tertiary-fixed)',
        'tertiary-fixed-dim': 'var(--tertiary-fixed-dim)',
        'on-tertiary-fixed': 'var(--on-tertiary-fixed)',
        'on-tertiary-fixed-variant': 'var(--on-tertiary-fixed-variant)',
        'background': 'var(--background)',
        'on-background': 'var(--on-background)',
        'surface-variant': 'var(--surface-variant)',
      },
      fontSize: {
        'display-lg': ['var(--font-size-display-lg)', { lineHeight: '80px', fontWeight: '800', letterSpacing: '-0.02em' }],
        'headline-lg': ['var(--font-size-headline-lg)', { lineHeight: '56px', fontWeight: '700', letterSpacing: '-0.01em' }],
        'headline-lg-mobile': ['var(--font-size-headline-lg-mobile)', { lineHeight: '40px', fontWeight: '700' }],
        'headline-md': ['var(--font-size-headline-md)', { lineHeight: '38px', fontWeight: '600' }],
        'body-lg': ['var(--font-size-body-lg)', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['var(--font-size-body-md)', { lineHeight: '24px', fontWeight: '400' }],
        'label-caps': ['var(--font-size-label-caps)', { lineHeight: '16px', fontWeight: '700', letterSpacing: '0.05em' }],
      },
      spacing: {
        'gutter': 'var(--spacing-gutter)',
        'stack-lg': 'var(--spacing-stack-lg)',
        'stack-md': 'var(--spacing-stack-md)',
        'stack-sm': 'var(--spacing-stack-sm)',
        'section-gap': 'var(--spacing-section-gap)',
        'container-max': 'var(--spacing-container-max)',
        'margin-mobile': 'var(--spacing-margin-mobile)',
        'margin-desktop': 'var(--spacing-margin-desktop)',
      },
      borderRadius: {
        'sm': 'var(--radius-sm)',
        'md': 'var(--radius-md)',
        'lg': 'var(--radius-lg)',
        'xl': 'var(--radius-xl)',
        'full': 'var(--radius-full)',
      },
      maxWidth: {
        'container-max': 'var(--spacing-container-max)',
      },
    },
  },
  plugins: [],
};
export default config;
